# Generated by Django 6.0.3 on 2026-03-12 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(default='', max_length=100)),
                ('quartier', models.CharField(blank=True, default='', max_length=100)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', max_length=20, verbose_name='Type de transaction')),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('local', 'Local commercial'), ('bureau', 'Bureau'), ('garage', 'Garage / Parking')], default='appartement', max_length=50)),
                ('prix', models.FloatField(help_text='Prix en FCFA')),
                ('surface', models.FloatField(help_text='Surface en m²')),
                ('nb_pieces', models.IntegerField(default=1, verbose_name='Nombre de pièces')),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL)),
                ('localisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bien', to='immobilier.localisation')),
            ],
            options={
                'verbose_name': 'Bien',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('vues', models.IntegerField(default=0)),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('dateExpiration', models.DateField(blank=True, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='immobilier.bien')),
            ],
            options={
                'verbose_name': 'Annonce',
                'ordering': ['-datePublication'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='immobilier.annonce')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to='biens/')),
                ('imagePrincipale', models.BooleanField(default=False)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='immobilier.bien')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='immobilier.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
    ]
